### ISSUE TITLE
can we use bower with you?

### ISSUE THREAD

**Issue by patrikx3** [xtoolkit/Micon#10]

**Comment by xtoolkit** [comment]
hi
could you explain more about collaboration and what should I do?
i working to make less & scss for gulp. next register micon to bower.
Did you mean register micon in the bower?

**Comment by patrikx3** [comment]
Do you not want to use with bower?
https://bower.io/docs/creating-packages/

Example form my repo: (most import is main directive):
https://github.com/patrikx3/resume-js-common/blob/master/bower.json

Once you have your bower.json, you can register with bower, like
bower register micon https://github.com/xtoolkit/Micon

**Comment by xtoolkit** [comment]
#11 micon registered in bower
