### ISSUE TITLE
Sass not working

### ISSUE THREAD

**Issue by ServerJunge** [xtoolkit/Micon#13]
Hi,

really like your Icons! I want to use the sass files but I got a problem. I only see square instead of the icons.

I changed the font-path to

     $mi-font-path:        "../fonts/" !default;

The fonts are in my public folder under fonts and my compiled css is in the public folder, too.

Do you have any idea?

**Comment by xtoolkit** [comment]
hi
thank you for report this problem.
found problem in https://github.com/sass/sass/issues/1395
fixed this problem with change font-awesome scss structure and use get icon var simple this https://github.com/sass/sass/issues/1395#issuecomment-65548751
sry for my bad english
